### ISSUE TITLE
8/22 ミーティング1

### ISSUE THREAD

**Issue by Kz-Iwata** [enpit2016fun/minipbl_d#1]
顔合わせ
今後やることなどの話し合い

**Comment by TogawaDaigo** [comment]
管理するアカウントの情報の決定
・名前（必須）
・住所（必須）
・郵便番号（必須）
・メールアドレス（配信希望の場合は必須）
・配信希望（必須）
・保育園に関連した兄弟情報（必須）
・卒業年（必須）

登録などは保育園のホームページで行う
現在はがきを送られている人にはQRコード付きのはがきを送ることで知らせる

**Comment by TogawaDaigo** [comment]
簡単な今日のアジェンダの決定

~12:10 顔合わせ・要求把握
12:10~13:10 昼休憩
13:10~14:00 全体振り返り
14:00~16:00 要求把握・要件定義・設計書
16:00~16:30 今日の振り返り
16:30~ 全体進捗発表

**Comment by TogawaDaigo** [comment]
メモ
・アカウントが必要なのは卒園生だけ
・年齢という項目が必要無い
・アカウント登録をホームページで行う
・希望者だけが登録する
・今のはがきの人は・・・？

**Comment by TogawaDaigo** [comment]
メール配信
・イベントごとにメールのテンプレを作成
・テンプレを１回登録すれば日付を変えるだけで送信できる
・新しいイベントは作る
・送信範囲は決めない

送る手順（通常）
メール送信ボタン
↓
イベント一覧
↓
各イベント詳細
↓
送信

送る手順（一覧に無い場合）
メール送信ボタン
↓
イベント一覧
↓
新イベント作成
↓
イベント登録
↓
送信

**Comment by TogawaDaigo** [comment]
イベントの情報
・日時
・場所
・イベントの説明（テンプレ化）
・保育園の連絡先（テンプレ化）
・今後の予定→選択式（プルダウンなど？）

**Comment by TogawaDaigo** [comment]
必要な主な機能

アカウント登録→年賀状作成
↓
メール配信（イベント登録）

Web（閲覧直近のイベント表示）

**Comment by TogawaDaigo** [comment]
![slack for ios upload 1](https://cloud.githubusercontent.com/assets/21018057/17845961/a3c750f0-6880-11e6-9bf5-fb7d9c1c517c.jpg)
メール送信のフロー図作成

**Comment by TogawaDaigo** [comment]
![slack for ios upload 3](https://cloud.githubusercontent.com/assets/21018057/17845986/c29dd882-6880-11e6-9918-917c996331ce.jpg)
アカウント登録のフロー図作成

**Comment by TogawaDaigo** [comment]
![default](https://cloud.githubusercontent.com/assets/21018057/17846557/48327036-6884-11e6-8389-4567750f00b2.jpg)
年賀状作成のフロー図作成

**Comment by TogawaDaigo** [comment]
開発はWeb系を使って行う
役割分担
室蘭工業大学（山田・山本）→アカウント登録・Web閲覧
はこだて未来大学（外川・岩田）→メール配信・年賀状作成
